# Generated by Django 4.2.5 on 2023-10-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_alter_tiposexames_tipo_solicitacaoexame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposexames',
            old_name='Disponivel',
            new_name='disponivel',
        ),
    ]
